# Generated by Django 2.1.1 on 2018-10-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCategory', models.CharField(max_length=50, null=True)),
                ('productName', models.CharField(max_length=50)),
                ('productPrice', models.IntegerField()),
                ('productDescription', models.TextField(null='True')),
                ('productPics', models.FileField(null='True', upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30, null='True')),
            ],
        ),
    ]
