# Generated by Django 2.1.1 on 2018-10-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZappyFoodApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='quantity',
            field=models.PositiveIntegerField(null='True'),
            preserve_default='True',
        ),
    ]
