# Generated by Django 2.1.1 on 2018-11-12 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZappyFoodApp', '0002_addproduct_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_address', models.CharField(max_length=400)),
                ('mobile', models.CharField(max_length=20)),
                ('images', models.ImageField(null='True', upload_to='Customers')),
                ('customer_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ZappyFoodApp.User')),
            ],
        ),
    ]
